AWSTemplateFormatVersion: '2010-09-09'
Description: Creates infrastructure resources for GameChart application.

Resources:

  AmplifyExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: amplify.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: Amplify
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "amplify:*"
                Resource: "*"

  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: GameChartApp
      Description: GameChart Amplify App
      OauthToken: '{{resolve:secretsmanager:GithubAccessToken:SecretString:AccessToken}}'
      IAMServiceRole: !GetAtt AmplifyExecutionRole.Arn
      Repository: '{{resolve:secretsmanager:GitHubRepoUrl:SecretString:Url}}'
      EnvironmentVariables:
        - Name: AMPLIFY_MONOREPO_APP_ROOT
          Value: application
        - Name: AMPLIFY_DIFF_DEPLOY
          Value: false
      BuildSpec: |-
        version: 1
        applications:
          - frontend:
              phases:
                preBuild:
                  commands:
                    - npm install
                build:
                  commands:
                    - npm run build
              artifacts:
                baseDirectory: build
                files:
                  - '**/*'
              cache:
                paths:
                  - node_modules/**/*
            appRoot: application

  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      BranchName: main
      AppId: !GetAtt AmplifyApp.AppId
      Description: Main Branch
      EnableAutoBuild: true

Outputs:
  DefaultDomain:
    Value: !GetAtt AmplifyApp.DefaultDomain