AWSTemplateFormatVersion: '2010-09-09'
Description: Creates infrastructure resources for GameChart application.

Parameters:
  MonitoringAccountIds:
    Description: Allows one or more monitoring accounts to view your data. Enter AWS account ids, 12 numeric digits in comma-separated list
    Type: CommaDelimitedList


Resources:

  GameChartApp:
    Type: AWS::Amplify::App
    Properties:
      Name: GameChartApp
      Description: GameChart Amplify App
      AccessToken: '{{resolve:secretsmanager:GithubAccessToken:SecretString:AccessToken}}'
      IAMServiceRole: String
      OauthToken: String
      Repository: String
      Tags: 
        - Tag

  